// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDImmxohXCGGv86ikDXFOpqKu2A0-UFJBs',
    appId: '1:246663366984:web:4dedfd894700d731f10b7d',
    messagingSenderId: '246663366984',
    projectId: 'aber-665ab',
    authDomain: 'aber-665ab.firebaseapp.com',
    storageBucket: 'aber-665ab.appspot.com',
    measurementId: 'G-DWYGJDQ6YM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCINjSgb2zfZG6eE3jkKqEswR-baHGXejs',
    appId: '1:246663366984:android:0b73e54ed93bead3f10b7d',
    messagingSenderId: '246663366984',
    projectId: 'aber-665ab',
    storageBucket: 'aber-665ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7jo0FMYOGNMQftZl9jTX-x128LhPowc',
    appId: '1:246663366984:ios:46d933106a701619f10b7d',
    messagingSenderId: '246663366984',
    projectId: 'aber-665ab',
    storageBucket: 'aber-665ab.appspot.com',
    iosClientId: '246663366984-mv5ppgg1a16prpi5mfs3stov2akuk9cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ7jo0FMYOGNMQftZl9jTX-x128LhPowc',
    appId: '1:246663366984:ios:46d933106a701619f10b7d',
    messagingSenderId: '246663366984',
    projectId: 'aber-665ab',
    storageBucket: 'aber-665ab.appspot.com',
    iosClientId: '246663366984-mv5ppgg1a16prpi5mfs3stov2akuk9cg.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiApp',
  );
}
